name: Daily Reddit Scraper
on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点运行
  workflow_dispatch:      # 允许手动触发

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install praw pandas

    - name: Run Scraper
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      run: |
        sed -i "s/YOUR_CLIENT_ID/$CLIENT_ID/g" scraper.py
        sed -i "s/YOUR_CLIENT_SECRET/$CLIENT_SECRET/g" scraper.py
        python scraper.py

    - name: Upload Results
      uses: actions/upload-artifact@v2
      with:
        name: reddit-videos
        path: hot_videos.csv
